before_cache:
- rm -rf $HOME/.m2/repository/org/keycloak
before_script:
- export MAVEN_SKIP_RC=true
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - MAVEN_SKIP_RC=true
  - MAVEN_OPTS="-Xms512m -Xmx2048m"
  matrix:
  - TESTS=group1
  - TESTS=group2
  - TESTS=group3
  - TESTS=group4
  - TESTS=adapter
  - TESTS=old
install:
- travis_wait 60 mvn install -Pdistribution -DskipTests=true -B -V -q
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- ./travis-run-tests.sh $TESTS
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: false
